import Head from 'next/head'
import { useRef, RefObject, useEffect } from 'react'
import { useRouter } from 'next/router'

import styles from '@/styles/Home.module.css'

import Navigator from './components/Navigator'

import { userToken } from './lib/userToken'

export default function Home() {
  const pointText = useRef<HTMLHeadingElement>(null)

  useEffect(() => {
    console.log(userToken)
    getToken()
  }, [])

  async function getToken() {
    if (userToken.name === '') return
    const data = await (await fetch(`/api/getPoint?name=${userToken.name}`)).json()
    if (data.StatusCode == 200) {
      (pointText as RefObject<HTMLHeadingElement>).current!.innerText = data.point
      console.log(data.point)
    } else {
      alert(`로그인에 실패했습니다.\nError ${data.error}`)
    }
  }

  return (
    <>
      <Head>
        <title>Dimi6</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" as="style" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard.css" />
      </Head>
      <Navigator></Navigator>
      <div className={styles.center}>
        <main className={styles.main}>
          <div className={styles.title}>
            <p>한국디지털미디어고등학교</p>
            <h1>1학년 6반 포인트 시스템</h1>
          </div>
          <div className={styles.notice}>
          <img src='megaphone.png' height={30}></img><p>다음주 화요일까지 학생종합 평가를 실시하세요</p>
          </div>
          {(userToken.name !== '') &&
            (<section className={styles.content}>
              <div className={styles.card}>
                <div className={styles.row}>
                  <h1 className={styles.point}>포인트</h1>
                  <h1 className={styles.moneyTitle}><span ref={pointText} className={styles.money}></span>p</h1>
                </div>
              </div>
              <div className={styles.card}>
                <h1>이벤트</h1>
                <p>10월 22일 박시혁의 생일</p>
              </div>
              <div className={styles.card}>
                <h1>오늘의 제제쌤</h1>
                <p>좋은 제자에게는 좋은 코치가 있다. </p>
              </div>
            </section>)
          }
          {(userToken.name === '') &&
            (<section className={styles.text}>
              <h1>로그인이 필요합니다.</h1>
            </section>)}
        </main>
      </div>
    </>
  )
}