import Head from 'next/head'
import { useRef, RefObject, useEffect, useState, MutableRefObject } from 'react'

import styles from '@/styles/Home.module.css'

import Navigator from './components/Navigator'

export default function Home() {
  const [isLogin, setIsLogin] = useState(false)
  const pointText = useRef<HTMLHeadingElement | {}>({})

  useEffect(() => {
    verify()
  }, [])

  async function verify() {
    const token = localStorage.getItem('token')
    if (token === '') return false
    const res = await fetch('/api/user/verify', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        token: token
      })
    })
    if (res.status === 200) {
      setIsLogin(true)
      getPoint()
    }
    else {
      setIsLogin(false)
      localStorage.removeItem('token')
    }
  }

  async function getPoint() {
    const token = localStorage.getItem('token')
    const res = await fetch(`/api/point/get?token=${token}`)
    const data = await res.json()
    if (res.status === 200) {
      (pointText as RefObject<HTMLHeadingElement>).current!.innerText = data.point
    }
  }

  return (
    <>
      <Head>
        <title>Dimi6</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/gh/sunn-us/SUIT/fonts/static/woff2/SUIT.css" rel="stylesheet"></link>
      </Head>
      <Navigator></Navigator>
      <div className={styles.center}>
        <main className={styles.main}>
          <div className={styles.title}>
            <p>한국디지털미디어고등학교</p>
            <h1>1학년 6반 포인트 시스템</h1>
          </div>
          <div className={styles.notice}>
          <img src='img/megaphone.png' height={30}></img><p>사이트를 제작 중입니다.</p>
          </div>
          {(isLogin) &&
            (<section className={styles.content}>
              <div className={styles.card}>
                <div className={styles.row}>
                  <h1 className={styles.point}>포인트</h1>
                  <h1 className={styles.moneyTitle}><span ref={pointText as MutableRefObject<HTMLHeadingElement>} className={styles.money}></span>p</h1>
                </div>
              </div>
              <div className={styles.card}>
                <h1>이벤트</h1>
                <p><b>8월 31일</b> 박종휘의 생일</p>
                <p><b>10월 1일</b> 최지윤의 생일</p>
                <p><b>10월 22일</b> 박시혁의 생일</p>
                <p><b>11월 5일</b> 주한결의 생일</p>
              </div>
              <div className={styles.card}>
                <h1>오늘의 제제쌤</h1>
                <p>좋은 제자에게는 좋은 코치가 있다. </p>
              </div>
            </section>)
          }
          {(!isLogin) &&
            (<section className={styles.text}>
              <h1>로그인이 필요합니다.</h1>
            </section>)}
        </main>
      </div>
    </>
  )
}