import Head from 'next/head'

import styles from '@/styles/shop.module.css'

import Navigator from './components/Navigator'

export default function shop() {
  async function getItems() {
    const res = await fetch('/api/shop/get')
    const data = await res.json()
    if (res.status === 200) {
      console.log(data)
    }
  }

  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" as="style" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard.css" />
      </Head>
      <Navigator></Navigator>
      <div className={styles.center}>
        <main className={styles.main}>
          <h1>교환소</h1>
          <section className={styles.items}>
            {
              
            }
            <div className={styles.item}>
              <img src='img/logo.png' className={styles.itemImage}/>
              <h2>금요귀가권</h2>
              <p>금요귀가권</p>
              <div className={styles.flex}>
                <img src='img/coin-small.svg' height={20}></img>
                <p><b>9999p</b></p>
              </div>
              <button>구매하기</button>
            </div>
          </section>
        </main>
      </div>
    </>
  )
}